version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "MarlinCliBackend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1src3xqx76wfq"
s3_prefix = "MarlinCliBackend"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
